let currentUser = null;

window.addEventListener('DOMContentLoaded', async () => {
  Telegram.WebApp.ready();
    Telegram.WebApp.expand();
      const tgUser = Telegram.WebApp.initDataUnsafe?.user || { id: 0 };
        currentUser = await getOrCreateUser(tgUser);
          if (!['owner','admin','senior_moderator','moderator'].includes(currentUser?.role)) {
              document.getElementById('reportsContent').innerHTML = '<div class="access-denied"><div class="empty-icon">🔒</div><p>Нет доступа</p></div>';
                  return;
                    }
                      await loadReports();
                      });

                      async function loadReports() {
                        const { data: reports } = await db
                            .from('reports')
                                .select(`*, listings(id,title,price), users!reports_reporter_id_fkey(id,username,first_name)`)
                                    .eq('status', 'pending')
                                        .order('created_at', { ascending: false });

                                          const container = document.getElementById('reportsContent');

                                            if (!reports || !reports.length) {
                                                container.innerHTML = `
                                                      <div class="empty-state">
                                                              <div class="empty-icon">✅</div>
                                                                      <p>Жалоб нет</p>
                                                                            </div>`;
                                                                                return;
                                                                                  }

                                                                                    container.innerHTML = reports.map(r => {
                                                                                        const reporter = r.users?.username
                                                                                              ? `@${r.users.username}` : r.users?.first_name || 'Пользователь';
                                                                                                  const listing = r.listings?.title || 'Объявление удалено';
                                                                                                      const date = new Date(r.created_at).toLocaleDateString('ru-RU');

                                                                                                          return `
                                                                                                                <div class="admin-card">
                                                                                                                        <div class="admin-card-header">
                                                                                                                                  <div>
                                                                                                                                              <div class="admin-card-title">🚩 ${r.reason}</div>
                                                                                                                                                          <div style="font-size:12px;color:var(--hint);margin-top:4px">
                                                                                                                                                                        От: ${reporter} · ${date}
                                                                                                                                                                                    </div>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                        <span class="status-badge status-pending">Новая</span>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                        <div class="admin-card-body">
                                                                                                                                                                                                                                  <div style="font-size:13px;margin-bottom:12px">
                                                                                                                                                                                                                                              Объявление: <b>${listing}</b>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                  <div class="btn-row">
                                                                                                                                                                                                                                                                              <button class="btn-primary" onclick="viewListing('${r.listing_id}')">Открыть</button>
                                                                                                                                                                                                                                                                                          <button class="btn-unban" onclick="resolveReport('${r.id}')">Принять</button>
                                                                                                                                                                                                                                                                                                      <button class="btn-ban" onclick="rejectReport('${r.id}')">Отклонить</button>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                              </div>`;
                                                                                                                                                                                                                                                                                                                                }).join('');
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                async function resolveReport(id) {
                                                                                                                                                                                                                                                                                                                                      await db.from('reports').update({
                                                                                                                                                                                                                                                                                                                                          status: 'resolved',
                                                                                                                                                                                                                                                                                                                                              moderator_id: currentUser.id
                                                                                                                                                                                                                                                                                                                                                }).eq('id', id);

                                                                                                                                                                                                                                                                                                                                                  await logAction('resolve_report', 'report', id, 'Жалоба принята');
                                                                                                                                                                                                                                                                                                                                                    showToast('Жалоба принята');
                                                                                                                                                                                                                                                                                                                                                      await loadReports();
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                      async function rejectReport(id) {
                                                                                                                                                                                                                                                                                                                                                        await db.from('reports').update({
                                                                                                                                                                                                                                                                                                                                                            status: 'rejected',
                                                                                                                                                                                                                                                                                                                                                                moderator_id: currentUser.id
                                                                                                                                                                                                                                                                                                                                                                  }).eq('id', id);

                                                                                                                                                                                                                                                                                                                                                                    await logAction('reject_report', 'report', id, 'Жалоба отклонена');
                                                                                                                                                                                                                                                                                                                                                                      showToast('Жалоба отклонена');
                                                                                                                                                                                                                                                                                                                                                                        await loadReports();
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        function viewListing(id) {
                                                                                                                                                                                                                                                                                                                                                                          window.location.href = `../pages/listing.html?id=${id}`;
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                          async function logAction(action, targetType, targetId, details) {
                                                                                                                                                                                                                                                                                                                                                                            await db.from('action_log').insert({
                                                                                                                                                                                                                                                                                                                                                                                user_id: currentUser.id,
                                                                                                                                                                                                                                                                                                                                                                                    action,
                                                                                                                                                                                                                                                                                                                                                                                        target_type: targetType,
                                                                                                                                                                                                                                                                                                                                                                                            target_id: String(targetId),
                                                                                                                                                                                                                                                                                                                                                                                                details
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                  function showToast(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                    const t = document.getElementById('toast');
                                                                                                                                                                                                                                                                                                                                                                                                      t.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                        t.classList.add('show');
                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => t.classList.remove('show'), 2500);
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                