let currentUser = null;
let adminStats = {};

const ADMIN_ROLES = ['owner', 'admin', 'senior_moderator', 'moderator', 'arbitrator'];

const ROLE_LABELS = {
  owner: 'Владелец',
    admin: 'Администратор',
      senior_moderator: 'Ст. Модератор',
        moderator: 'Модератор',
          arbitrator: 'Арбитр'
          };

          window.addEventListener('DOMContentLoaded', async () => {
            Telegram.WebApp.ready();
              Telegram.WebApp.expand();

                const tgUser = Telegram.WebApp.initDataUnsafe?.user || {
                    id: 0, first_name: 'Гость', username: 'guest'
                      };
                        currentUser = await getOrCreateUser(tgUser);

                          if (!ADMIN_ROLES.includes(currentUser?.role)) {
                              document.getElementById('accessDenied').style.display = 'flex';
                                  return;
                                    }

                                      document.getElementById('adminContent').style.display = 'block';

                                        const roleBadge = document.getElementById('adminRole');
                                          roleBadge.textContent = ROLE_LABELS[currentUser.role] || currentUser.role;
                                            roleBadge.className = `role-badge role-${currentUser.role}`;

                                              await loadStats();
                                                renderMenu();
                                                });

                                                async function loadStats() {
                                                  const [
                                                      { count: usersCount },
                                                          { count: listingsCount },
                                                              { count: activeCount },
                                                                  { count: reportsCount }
                                                                    ] = await Promise.all([
                                                                        db.from('users').select('*', { count: 'exact', head: true }),
                                                                            db.from('listings').select('*', { count: 'exact', head: true }),
                                                                                db.from('listings').select('*', { count: 'exact', head: true }).eq('status', 'active'),
                                                                                    db.from('reports').select('*', { count: 'exact', head: true }).eq('status', 'pending')
                                                                                      ]);

                                                                                        adminStats = { usersCount, listingsCount, activeCount, reportsCount };

                                                                                          document.getElementById('adminStats').innerHTML = `
                                                                                              <div class="admin-stat-card">
                                                                                                    <div class="admin-stat-value">${usersCount || 0}</div>
                                                                                                          <div class="admin-stat-label">Пользователей</div>
                                                                                                              </div>
                                                                                                                  <div class="admin-stat-card">
                                                                                                                        <div class="admin-stat-value">${listingsCount || 0}</div>
                                                                                                                              <div class="admin-stat-label">Объявлений</div>
                                                                                                                                  </div>
                                                                                                                                      <div class="admin-stat-card">
                                                                                                                                            <div class="admin-stat-value">${activeCount || 0}</div>
                                                                                                                                                  <div class="admin-stat-label">Активных</div>
                                                                                                                                                      </div>
                                                                                                                                                          <div class="admin-stat-card">
                                                                                                                                                                <div class="admin-stat-value" style="color:${reportsCount > 0 ? '#ff5050' : 'var(--accent)'}">
                                                                                                                                                                        ${reportsCount || 0}
                                                                                                                                                                              </div>
                                                                                                                                                                                    <div class="admin-stat-label">Жалоб</div>
                                                                                                                                                                                        </div>`;
                                                                                                                                                                                        }
                                                                                                                                                                                        function renderMenu() {
                                                                                                                                                                                              const role = currentUser.role;
                                                                                                                                                                                                const isOwnerOrAdmin = ['owner', 'admin'].includes(role);
                                                                                                                                                                                                  const isMod = ['owner', 'admin', 'senior_moderator', 'moderator'].includes(role);

                                                                                                                                                                                                    const sections = [];

                                                                                                                                                                                                      if (isMod) {
                                                                                                                                                                                                          sections.push({
                                                                                                                                                                                                                title: 'Модерация',
                                                                                                                                                                                                                      items: [
                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                        icon: '🚩',
                                                                                                                                                                                                                                                  name: 'Жалобы',
                                                                                                                                                                                                                                                            desc: 'Обработка жалоб пользователей',
                                                                                                                                                                                                                                                                      badge: adminStats.reportsCount || 0,
                                                                                                                                                                                                                                                                                href: 'reports.html'
                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                          icon: '📋',
                                                                                                                                                                                                                                                                                                                    name: 'Объявления',
                                                                                                                                                                                                                                                                                                                              desc: 'Управление объявлениями',
                                                                                                                                                                                                                                                                                                                                        href: 'listings.html'
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                              if (isOwnerOrAdmin) {
                                                                                                                                                                                                                                                                                                                                                                  sections.push({
                                                                                                                                                                                                                                                                                                                                                                        title: 'Управление',
                                                                                                                                                                                                                                                                                                                                                                              items: [
                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                icon: '👥',
                                                                                                                                                                                                                                                                                                                                                                                                          name: 'Пользователи',
                                                                                                                                                                                                                                                                                                                                                                                                                    desc: 'Поиск, блокировки, роли',
                                                                                                                                                                                                                                                                                                                                                                                                                              href: 'users.html'
                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon: '🗺',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name: 'Серверы',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            desc: 'Добавить, отключить сервер',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href: 'servers.html'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon: '🗂',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: 'Категории',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    desc: 'Управление категориями',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href: 'categories.html'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sections.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: 'Система',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                items: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  icon: '📜',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: 'Журнал действий',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      desc: 'История всех действий администрации',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href: 'logs.html'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon: '⚙️',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: 'Настройки',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              desc: 'Параметры проекта',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href: 'settings.html'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('adminMenu').innerHTML = sections.map(section => `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="admin-menu-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="admin-menu-title">${section.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ${section.items.map(item => `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="admin-menu-item" onclick="window.location.href='${item.href}'">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="admin-menu-icon">${item.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="admin-menu-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="admin-menu-name">${item.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="admin-menu-desc">${item.desc}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ${item.badge ? `<div class="badge-count">${item.badge}</div>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="admin-menu-arrow">›</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>`).join('')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>`).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function showToast(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const t = document.getElementById('toast');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                t.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  t.classList.add('show');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => t.classList.remove('show'), 2500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                        }