let currentUser = null;
let searchTimeout = null;

const ROLES = ['user','moderator','senior_moderator','arbitrator','admin','owner'];
const ROLE_LABELS = {
  user: 'Пользователь',
    moderator: 'Модератор',
      senior_moderator: 'Ст. Модератор',
        arbitrator: 'Арбитр',
          admin: 'Администратор',
            owner: 'Владелец'
            };

            window.addEventListener('DOMContentLoaded', async () => {
              Telegram.WebApp.ready();
                Telegram.WebApp.expand();
                  const tgUser = Telegram.WebApp.initDataUnsafe?.user || { id: 0 };
                    currentUser = await getOrCreateUser(tgUser);
                      if (!['owner','admin','senior_moderator'].includes(currentUser?.role)) {
                          document.getElementById('usersContent').innerHTML =
                                '<div class="access-denied"><div class="empty-icon">🔒</div><p>Нет доступа</p></div>';
                                  }
                                  });

                                  function searchUsers(value) {
                                    clearTimeout(searchTimeout);
                                      if (!value.trim()) return;
                                        searchTimeout = setTimeout(() => runSearch(value), 500);
                                        }

                                        async function runSearch(query) {
                                          const container = document.getElementById('usersContent');
                                            container.innerHTML = '<div style="text-align:center;color:var(--hint);padding:20px">Поиск...</div>';

                                              const { data: users } = await db
                                                  .from('users')
                                                      .select('*')
                                                          .or(`username.ilike.%${query}%,first_name.ilike.%${query}%`)
                                                              .limit(20);

                                                                if (!users || !users.length) {
                                                                    container.innerHTML = '<div class="empty-state"><div class="empty-icon">👤</div><p>Не найдено</p></div>';
                                                                        return;
                                                                          }

                                                                            container.innerHTML = users.map(u => renderUserCard(u)).join('');
                                                                            }

                                                                            function renderUserCard(u) {
                                                                              const name = [u.first_name, u.last_name].filter(Boolean).join(' ');
                                                                                const username = u.username ? `@${u.username}` : `ID: ${u.id}`;
                                                                                  const role = ROLE_LABELS[u.role] || u.role;
                                                                                    const banned = u.is_banned;
                                                                                      const scam = u.is_scam;

                                                                                        return `
                                                                                            <div class="admin-card" id="user-${u.id}">
                                                                                                  <div class="admin-card-header">
                                                                                                          <div>
                                                                                                                    <div class="admin-card-title">${name}</div>
                                                                                                                              <div style="font-size:12px;color:var(--hint);margin-top:2px">${username}</div>
                                                                                                                                        ${scam ? '<div class="scam-badge" style="margin-top:4px">⚠️ SCAM</div>' : ''}
                                                                                                                                                </div>
                                                                                                                                                        <span class="status-badge ${banned ? 'status-rejected' : 'status-resolved'}">
                                                                                                                                                                  ${banned ? 'Заблокирован' : role}
                                                                                                                                                                          </span>
                                                                                                                                                                                </div>
                                                                                                                                                                                      <div class="admin-card-body">
                                                                                                                                                                                              <div style="font-size:12px;color:var(--hint);margin-bottom:10px">
                                                                                                                                                                                                        ★ ${u.rating || '0.0'} · Сделок: ${u.deals_count || 0} · 
                                                                                                                                                                                                                  Регистрация: ${new Date(u.created_at).toLocaleDateString('ru-RU')}
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                  <div class="btn-row">
                                                                                                                                                                                                                                            ${!banned
                                                                                                                                                                                                                                                        ? `<button class="btn-ban" onclick="banUser(${u.id})">Заблокировать</button>`
                                                                                                                                                                                                                                                                    : `<button class="btn-unban" onclick="unbanUser(${u.id})">Разблокировать</button>`}
                                                                                                                                                                                                                                                                              ${!scam
                                                                                                                                                                                                                                                                                          ? `<button class="btn-warn" onclick="markScam(${u.id})">⚠️ SCAM</button>`
                                                                                                                                                                                                                                                                                                      : `<button class="btn-warn" onclick="removeScam(${u.id})">Снять SCAM</button>`}
                                                                                                                                                                                                                                                                                                                ${['owner','admin'].includes(currentUser?.role)
                                                                                                                                                                                                                                                                                                                            ? `<button class="btn-primary" onclick="openChangeRole(${u.id},'${u.role}')">Роль</button>`
                                                                                                                                                                                                                                                                                                                                        : ''}
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                        <div id="role-selector-${u.id}" style="display:none;margin-top:10px">
                                                                                                                                                                                                                                                                                                                                                                  <select onchange="changeRole(${u.id}, this.value)"
                                                                                                                                                                                                                                                                                                                                                                              style="width:100%;padding:10px;background:var(--bg2);border:1px solid var(--border);border-radius:8px;color:var(--text);font-size:14px">
                                                                                                                                                                                                                                                                                                                                                                                          ${ROLES.map(r => `<option value="${r}" ${r === u.role ? 'selected' : ''}>${ROLE_LABELS[r]}</option>`).join('')}
                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      async function banUser(userId) {
                                                                                                                                                                                                                                                                                                                                                                                                                          await db.from('users').update({
                                                                                                                                                                                                                                                                                                                                                                                                                              is_banned: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                  ban_reason: 'Заблокирован модератором'
                                                                                                                                                                                                                                                                                                                                                                                                                                    }).eq('id', userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                      await logAction('ban_user', 'user', userId, 'Пользователь заблокирован');
                                                                                                                                                                                                                                                                                                                                                                                                                                        showToast('Пользователь заблокирован');
                                                                                                                                                                                                                                                                                                                                                                                                                                          refreshUser(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                          async function unbanUser(userId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            await db.from('users').update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                is_banned: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ban_reason: null
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }).eq('id', userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        await logAction('unban_user', 'user', userId, 'Блокировка снята');
                                                                                                                                                                                                                                                                                                                                                                                                                                                          showToast('Блокировка снята');
                                                                                                                                                                                                                                                                                                                                                                                                                                                            refreshUser(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function markScam(userId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db.from('users').update({ is_scam: true }).eq('id', userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                await logAction('mark_scam', 'user', userId, 'Отметка SCAM поставлена');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  showToast('Отметка SCAM поставлена');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    refreshUser(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function removeScam(userId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await db.from('users').update({ is_scam: false }).eq('id', userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await logAction('remove_scam', 'user', userId, 'Отметка SCAM снята');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showToast('Отметка SCAM снята');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            refreshUser(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function openChangeRole(userId, currentRole) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const sel = document.getElementById(`role-selector-${userId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sel.style.display = sel.style.display === 'none' ? 'block' : 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async function changeRole(userId, newRole) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await db.from('users').update({ role: newRole }).eq('id', userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await logAction('change_role', 'user', userId, `Роль изменена на ${newRole}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      showToast('Роль изменена');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        refreshUser(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async function refreshUser(userId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { data: u } = await db.from('users').select('*').eq('id', userId).single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (u) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const card = document.getElementById(`user-${userId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (card) card.outerHTML = renderUserCard(u);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function logAction(action, targetType, targetId, details) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await db.from('action_log').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user_id: currentUser.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                action,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target_type: targetType,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target_id: String(targetId),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            details
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function showToast(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const t = document.getElementById('toast');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  t.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    t.classList.add('show');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setTimeout(() => t.classList.remove('show'), 2500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      