let currentUser = null;
let myListings = [];
let activeTab = 'active';

window.addEventListener('DOMContentLoaded', async () => {
  Telegram.WebApp.ready();
    Telegram.WebApp.expand();

      const tgUser = Telegram.WebApp.initDataUnsafe?.user || {
          id: 0, first_name: 'Гость', username: 'guest'
            };
              currentUser = await getOrCreateUser(tgUser);
                myListings = await getUserListings(currentUser.id);
                  renderProfile(tgUser);
                  });

                  function renderProfile(tgUser) {
                    const avatarHtml = tgUser.photo_url
                        ? `<img src="${tgUser.photo_url}" alt="avatar">`
                            : (tgUser.first_name || 'G')[0].toUpperCase();

                              const name = [tgUser.first_name, tgUser.last_name].filter(Boolean).join(' ');
                                const username = tgUser.username ? `@${tgUser.username}` : '';
                                  const rating = currentUser?.rating || '0.0';
                                    const deals = currentUser?.deals_count || 0;
                                      const reviews = currentUser?.reviews_count || 0;

                                        const activeCount = myListings.filter(l => l.status === 'active').length;
                                          const soldCount = myListings.filter(l => l.status === 'sold').length;
                                            const totalViews = myListings.reduce((sum, l) => sum + (l.views_count || 0), 0);

                                              document.getElementById('profileContent').innerHTML = `
                                                  <div class="profile-header">
                                                        <div class="profile-avatar">${avatarHtml}</div>
                                                              <div class="profile-info">
                                                                      <div class="profile-name">${name}</div>
                                                                              ${username ? `<div class="profile-username">${username}</div>` : ''}
                                                                                      <div class="profile-rating">
                                                                                                <span class="stars">★</span>
                                                                                                          <span>${rating}</span>
                                                                                                                    <span style="color:var(--hint);font-size:12px">(${reviews} отзывов)</span>
                                                                                                                            </div>
                                                                                                                                  </div>
                                                                                                                                      </div>

                                                                                                                                          <div class="profile-stats">
                                                                                                                                                <div class="stat-item">
                                                                                                                                                        <div class="stat-value">${activeCount}</div>
                                                                                                                                                                <div class="stat-label">Активных</div>
                                                                                                                                                                      </div>
                                                                                                                                                                            <div class="stat-item">
                                                                                                                                                                                    <div class="stat-value">${soldCount}</div>
                                                                                                                                                                                            <div class="stat-label">Продано</div>
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                        <div class="stat-item">
                                                                                                                                                                                                                <div class="stat-value">${totalViews}</div>
                                                                                                                                                                                                                        <div class="stat-label">Просмотров</div>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                      <div class="profile-menu">
                                                                                                                                                                                                                                            <div class="menu-item" onclick="window.location.href='favorites.html'">
                                                                                                                                                                                                                                                    <span class="menu-icon">❤️</span>
                                                                                                                                                                                                                                                            <span class="menu-text">Избранное</span>
                                                                                                                                                                                                                                                                    <span class="menu-arrow">›</span>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                <div class="menu-item" onclick="showToast('Скоро будет доступно')">
                                                                                                                                                                                                                                                                                        <span class="menu-icon">✉️</span>
                                                                                                                                                                                                                                                                                                <span class="menu-text">Сообщения</span>
                                                                                                                                                                                                                                                                                                        <span class="menu-arrow">›</span>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                    <div class="menu-item" onclick="showToast('Скоро будет доступно')">
                                                                                                                                                                                                                                                                                                                            <span class="menu-icon">🔔</span>
                                                                                                                                                                                                                                                                                                                                    <span class="menu-text">Уведомления</span>
                                                                                                                                                                                                                                                                                                                                            <span class="menu-arrow">›</span>
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                        <div class="menu-item" onclick="window.location.href='create.html'">
                                                                                                                                                                                                                                                                                                                                                                <span class="menu-icon">➕</span>
                                                                                                                                                                                                                                                                                                                                                                        <span class="menu-text">Подать объявление</span>
                                                                                                                                                                                                                                                                                                                                                                                <span class="menu-arrow">›</span>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                              <div class="listings-section">
                                                                                                                                                                                                                                                                                                                                                                                                    <div class="section-tabs">
                                                                                                                                                                                                                                                                                                                                                                                                            <button class="tab-btn active" onclick="switchTab('active', this)">Активные</button>
                                                                                                                                                                                                                                                                                                                                                                                                                    <button class="tab-btn" onclick="switchTab('expired', this)">Истёкшие</button>
                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="tab-btn" onclick="switchTab('sold', this)">Проданные</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div id="myListingsGrid"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>`;

                                                                                                                                                                                                                                                                                                                                                                                                                                              renderMyListings();
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                              function switchTab(tab, el) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                activeTab = tab;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                    el.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderMyListings();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                      function renderMyListings() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const now = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const filtered = myListings.filter(l => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (activeTab === 'active') return l.status === 'active' && new Date(l.expires_at) > now;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (activeTab === 'expired') return l.status === 'active' && new Date(l.expires_at) <= now;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (activeTab === 'sold') return l.status === 'sold';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const grid = document.getElementById('myListingsGrid');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!filtered.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    grid.innerHTML = `<div class="empty-state"><div class="empty-icon">📭</div><p>Нет объявлений</p></div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            grid.innerHTML = filtered.map(l => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const photo = l.listing_photos?.[0]?.url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const photoEl = photo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? `<img src="${photo}" alt="">`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : (l.categories?.icon || '📦');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const price = Number(l.price).toLocaleString('ru-RU');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const isExpired = new Date(l.expires_at) <= new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const statusClass = l.status === 'sold' ? 'status-sold' : isExpired ? 'status-expired' : 'status-active';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const statusText = l.status === 'sold' ? 'Продано' : isExpired ? 'Истекло' : 'Активно';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const actions = l.status !== 'sold' ? `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="my-listing-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ${isExpired ? `<button class="btn-small btn-extend" onclick="extendMyListing('${l.id}')">Продлить</button>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button class="btn-small btn-delete" onclick="deleteMyListing('${l.id}')">Удалить</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>` : '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="my-listing-card" onclick="openListing('${l.id}')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="my-listing-photo">${photoEl}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="my-listing-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="my-listing-title">${l.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="my-listing-price">${price} ₽</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="my-listing-status ${statusClass}">${statusText}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${actions}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async function extendMyListing(id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await extendListing(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    myListings = await getUserListings(currentUser.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderMyListings();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        showToast('Объявление продлено на 6 часов');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async function deleteMyListing(id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await deleteListing(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            myListings = myListings.filter(l => l.id !== id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderMyListings();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                showToast('Объявление удалено');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function openListing(id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.location.href = `listing.html?id=${id}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function showToast(msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const t = document.getElementById('toast');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      t.textContent = msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        t.classList.add('show');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => t.classList.remove('show'), 2500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }